const CONSTANTS = {
    REQUEST_PROPERTY: 'REQUEST_PROPERTY',
    REFRESH_PROPERTY: 'REFRESH_PROPERTY',
    REFRESH_PROPERTY_CONTENT: 'REFRESH_PROPERTY_CONTENT',
    REFRESH_SAVED_PROPERTY: 'REFRESH_SAVED_PROPERTY',
    REFRESH_PROPERTY_ERROR: 'REFRESH_PROPERTY_ERROR',
    REFRESH_IS_FETCHING: 'REFRESH_IS_FETCHING',
    ADD_SAVED_PROPERTY: 'ADD_SAVED_PROPERTY',
    REMOVE_SAVED_PROPERTY: 'REMOVE_SAVED_PROPERTY'
}

export default CONSTANTS
